import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kategori_combobox(object):
    def setupUi(self, kategori_combobox):
        kategori_combobox.setObjectName("MainWindow")
        kategori_combobox.resize(1200, 1000)
        kategori_combobox.setObjectName("kategori_combobox")
        self.centralwidget = QtWidgets.QWidget(kategori_combobox)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.kaydetbutton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kaydetbutton.setFont(font)
        self.kaydetbutton.setMinimumSize(QtCore.QSize(150, 50))
        self.kaydetbutton.setIconSize(QtCore.QSize(20, 20))
        self.kaydetbutton.setObjectName("kaydetbutton")
        self.gridLayout_5.addWidget(self.kaydetbutton, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 5, 0, 2, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.kaydetme_listbox = QtWidgets.QListView(self.centralwidget)
        self.kaydetme_listbox.setObjectName("kaydetme_listbox")
        self.horizontalLayout.addWidget(self.kaydetme_listbox)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 2, 7, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.yenilebutton = QtWidgets.QCommandLinkButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/png-transparent-computer-icons-refresh-computer-monochrome-arrow-icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.yenilebutton.setIcon(icon)
        self.yenilebutton.setIconSize(QtCore.QSize(60, 60))
        self.yenilebutton.setObjectName("yenilebutton")
        self.horizontalLayout_5.addWidget(self.yenilebutton)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 0, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.geributton = QtWidgets.QCommandLinkButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/pngtree-vector-back-icon-png-image_4190818.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.geributton.setIcon(icon1)
        self.geributton.setIconSize(QtCore.QSize(60, 60))
        self.geributton.setObjectName("geributton")
        self.gridLayout_6.addWidget(self.geributton, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.farkli_kategori_text = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.farkli_kategori_text.setFont(font)
        self.farkli_kategori_text.setObjectName("farkli_kategori_text")
        self.gridLayout_3.addWidget(self.farkli_kategori_text, 1, 1, 1, 1)
        self.kategori_combobox_2 = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kategori_combobox_2.setFont(font)
        self.kategori_combobox_2.setObjectName("kategori_combobox_2")
        self.gridLayout_3.addWidget(self.kategori_combobox_2, 0, 1, 1, 1)
        self.farkli_kategori_button = QtWidgets.QPushButton(self.centralwidget)
        self.farkli_kategori_button.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.farkli_kategori_button.setFont(font)
        self.farkli_kategori_button.setObjectName("farkli_kategori_button")
        self.gridLayout_3.addWidget(self.farkli_kategori_button, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 4, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.stokkoduekle_text = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stokkoduekle_text.setFont(font)
        self.stokkoduekle_text.setObjectName("stokkoduekle_text")
        self.gridLayout.addWidget(self.stokkoduekle_text, 0, 1, 1, 1)
        self.isimtext = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.isimtext.setFont(font)
        self.isimtext.setObjectName("isimtext")
        self.gridLayout.addWidget(self.isimtext, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.resimsecbutton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resimsecbutton.setFont(font)
        self.resimsecbutton.setMinimumSize(QtCore.QSize(150, 50))
        self.resimsecbutton.setObjectName("resimsecbutton")
        self.gridLayout_2.addWidget(self.resimsecbutton, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.resim_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resim_label.setFont(font)
        self.resim_label.setObjectName("resim_label")
        self.gridLayout_2.addWidget(self.resim_label, 2, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 0, 2, 1)
        kategori_combobox.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(kategori_combobox)
        self.statusbar.setObjectName("statusbar")
        kategori_combobox.setStatusBar(self.statusbar)

        self.retranslateUi(kategori_combobox)
        QtCore.QMetaObject.connectSlotsByName(kategori_combobox)

    def retranslateUi(self, kategori_combobox):
        _translate = QtCore.QCoreApplication.translate
        kategori_combobox.setWindowTitle(_translate("kategori_combobox", "MainWindow"))
        self.kaydetbutton.setText(_translate("kategori_combobox", "KAYDET"))
        self.yenilebutton.setText(_translate("kategori_combobox", "YENİLE"))
        self.geributton.setText(_translate("kategori_combobox", "GERİ"))
        self.label_5.setText(_translate("kategori_combobox", "Kategori: "))
        self.farkli_kategori_button.setText(_translate("kategori_combobox", "Farklı kategori ekle"))
        self.label.setText(_translate("kategori_combobox", "Stok kodu: "))
        self.label_2.setText(_translate("kategori_combobox", "İsmi, açıklama: "))
        self.resimsecbutton.setText(_translate("kategori_combobox", "Resim seç"))
        self.label_3.setText(_translate("kategori_combobox", "Resim: "))
        self.resim_label.setText(_translate("kategori_combobox", ""))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_kategori_combobox()
    ui.setupUi(MainWindow)

    screen = app.primaryScreen()
    if screen is not None:
        screen_geometry = screen.geometry()
        x = (screen_geometry.width() - MainWindow.width()) // 2
        y = (screen_geometry.height() - MainWindow.height()) // 2
        MainWindow.move(x, y)

    MainWindow.show()
    sys.exit(app.exec_())