from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.malzemelist = QtWidgets.QTableView(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.malzemelist.setObjectName("malzemelist")
        self.malzemelist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.malzemelist.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.malzemelist.horizontalHeader().setStretchLastSection(True) # type: ignore
        self.malzemelist.verticalHeader().setVisible(False) # type: ignore
        self.gridLayout.addWidget(self.malzemelist, 5, 0, 5, 6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 9, 1, 1)
        self.duzenlebutton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.duzenlebutton.setFont(font)
        self.duzenlebutton.setObjectName("duzenlebutton")
        self.duzenlebutton.setMinimumSize(QtCore.QSize(150, 50))
        self.gridLayout.addWidget(self.duzenlebutton, 2, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 9, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 9, 1, 1)
        self.chosenmalzeme_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chosenmalzeme_label.setFont(font)
        self.chosenmalzeme_label.setObjectName("chosenmalzeme_label")
        self.gridLayout.addWidget(self.chosenmalzeme_label, 2, 8, 1, 2)
        self.silbutton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.silbutton.setFont(font)
        self.silbutton.setMinimumSize(QtCore.QSize(150, 50))
        self.silbutton.setObjectName("silbutton")
        self.gridLayout.addWidget(self.silbutton, 3, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 6, 1, 1)
        self.eklebutton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.eklebutton.setFont(font)
        self.eklebutton.setMinimumSize(QtCore.QSize(150, 50))
        self.eklebutton.setObjectName("eklebutton")
        self.gridLayout.addWidget(self.eklebutton, 3, 4, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 3, 1, 1)
        self.arabutton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.arabutton.setFont(font)
        self.arabutton.setMinimumSize(QtCore.QSize(150, 50))
        self.arabutton.setObjectName("arabutton")
        self.gridLayout.addWidget(self.arabutton, 2, 2, 1, 1)
        self.searchbox = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchbox.setFont(font)
        self.searchbox.setText("")
        self.searchbox.setObjectName("searchbox")
        self.gridLayout.addWidget(self.searchbox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 6, 1, 1)
        self.urunfotograf_display = QtWidgets.QGraphicsView(self.centralwidget)
        self.urunfotograf_display.setMinimumSize(1000, 1378)
        self.urunfotograf_display.setObjectName("urunfotograf_display")
        self.gridLayout.addWidget(self.urunfotograf_display, 5, 6, 1, 4)
        self.stickerolustur_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stickerolustur_button.setFont(font)
        self.stickerolustur_button.setMinimumSize(QtCore.QSize(200, 50))
        self.stickerolustur_button.setObjectName("stickerolustur_button")
        self.gridLayout.addWidget(self.stickerolustur_button, 3, 6, 1, 2)
        
        self.yenilebutton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yenilebutton.setFont(font)
        self.yenilebutton.setMinimumSize(QtCore.QSize(150, 50))
        self.yenilebutton.setObjectName("yenilebutton")
        self.gridLayout.addWidget(self.yenilebutton, 2, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Ürün ismi: "))
        self.duzenlebutton.setText(_translate("MainWindow", "DÜZENLE"))
        self.chosenmalzeme_label.setText(_translate("MainWindow", ""))
        self.silbutton.setText(_translate("MainWindow", "SİL"))
        self.label.setText(_translate("MainWindow", "Seçilen malzeme: "))
        self.eklebutton.setText(_translate("MainWindow", "EKLE"))
        self.arabutton.setText(_translate("MainWindow", "ARA"))
        self.label_2.setText(_translate("MainWindow", "Ürün Fotoğrafı: "))
        self.stickerolustur_button.setText(_translate("MainWindow", "Sticker oluştur ve zimmetle"))
        self.yenilebutton.setText(_translate("MainWindow", "YENİLE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())
