from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.secilmismalzeme_bilgiler = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.secilmismalzeme_bilgiler.setFont(font)
        self.secilmismalzeme_bilgiler.setObjectName("secilmismalzeme_bilgiler")
        self.gridLayout.addWidget(self.secilmismalzeme_bilgiler, 1, 0, 3, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.geri_button = QtWidgets.QCommandLinkButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/pngtree-vector-back-icon-png-image_4190818.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.geri_button.setIcon(icon)
        self.geri_button.setIconSize(QtCore.QSize(60, 60))
        self.geri_button.setObjectName("geri_button")
        self.gridLayout.addWidget(self.geri_button, 9, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.sahissil_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sahissil_button.setFont(font)
        self.sahissil_button.setMinimumSize(QtCore.QSize(150, 50))
        self.sahissil_button.setObjectName("sahissil_button")
        self.gridLayout.addWidget(self.sahissil_button, 4, 2, 1, 1)
        self.stickerview = QtWidgets.QGraphicsView(self.centralwidget)
        self.stickerview.setObjectName("stickerview")
        self.gridLayout.addWidget(self.stickerview, 8, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.sahisisim_text = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sahisisim_text.setFont(font)
        self.sahisisim_text.setObjectName("sahisisim_text")
        self.gridLayout.addWidget(self.sahisisim_text, 1, 2, 1, 2)
        self.kisi_combobox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kisi_combobox.setFont(font)
        self.kisi_combobox.setObjectName("kisi_combobox")
        self.gridLayout.addWidget(self.kisi_combobox, 0, 2, 1, 2)
        self.bulundugukat_combobox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bulundugukat_combobox.setFont(font)
        self.bulundugukat_combobox.setObjectName("bulundugukat_combobox")
        self.gridLayout.addWidget(self.bulundugukat_combobox, 2, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.bulundugusube_combobox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bulundugusube_combobox.setFont(font)
        self.bulundugusube_combobox.setObjectName("bulundugusube_combobox")
        self.gridLayout.addWidget(self.bulundugusube_combobox, 3, 2, 1, 2)
        self.sahisekle_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sahisekle_button.setFont(font)
        self.sahisekle_button.setMinimumSize(QtCore.QSize(150, 50))
        self.sahisekle_button.setObjectName("sahisekle_button")
        self.gridLayout.addWidget(self.sahisekle_button, 4, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.zimmetlebutton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zimmetlebutton.setFont(font)
        self.zimmetlebutton.setMinimumSize(QtCore.QSize(150, 50))
        self.zimmetlebutton.setObjectName("zimmetlebutton")
        self.horizontalLayout.addWidget(self.zimmetlebutton)
        self.zimmetlesil_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zimmetlesil_button.setFont(font)
        self.zimmetlesil_button.setMinimumSize(QtCore.QSize(150, 50))
        self.zimmetlesil_button.setObjectName("zimmetlesil_button")
        self.horizontalLayout.addWidget(self.zimmetlesil_button)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 2, 2)
        self.zimmetduzenle_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zimmetduzenle_button.setFont(font)
        self.zimmetduzenle_button.setMinimumSize(QtCore.QSize(150, 50))
        self.zimmetduzenle_button.setObjectName("zimmetduzenle_button")
        self.gridLayout.addWidget(self.zimmetduzenle_button, 7, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.secilmismalzeme_bilgiler.setText(_translate("MainWindow", ""))
        self.label_5.setText(_translate("MainWindow", "Seçilen ürün: "))
        self.geri_button.setText(_translate("MainWindow", "GERİ"))
        self.label_4.setText(_translate("MainWindow", "Bulunduğu Şube: "))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.sahissil_button.setText(_translate("MainWindow", "Şahıs sil"))
        self.label_2.setText(_translate("MainWindow", "Tam İsim: "))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.label.setText(_translate("MainWindow", "Şahıs: "))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_3.setText(_translate("MainWindow", "Bulunduğu Kat: "))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.sahisekle_button.setText(_translate("MainWindow", "Şahıs Ekle"))
        self.zimmetlebutton.setText(_translate("MainWindow", "Sticker oluştur ve zimmetle"))
        self.zimmetlesil_button.setText(_translate("MainWindow", "Zimmetleneni sil"))
        self.zimmetduzenle_button.setText(_translate("MainWindow", "Zimmetlenen Düzenle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())
