import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 9, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 8, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 7, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 6, 0, 1, 1)
        self.yenizimmetbilgi_text = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yenizimmetbilgi_text.setFont(font)
        self.yenizimmetbilgi_text.setObjectName("yenizimmetbilgi_text")
        self.gridLayout.addWidget(self.yenizimmetbilgi_text, 7, 1, 2, 2)
        self.zimmetlekaydetyeni_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zimmetlekaydetyeni_button.setFont(font)
        self.zimmetlekaydetyeni_button.setMinimumSize(QtCore.QSize(150, 50))
        self.zimmetlekaydetyeni_button.setObjectName("zimmetlekaydetyeni_button")
        self.gridLayout.addWidget(self.zimmetlekaydetyeni_button, 6, 2, 1, 1)
        self.yenizimmetle = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yenizimmetle.setFont(font)
        self.yenizimmetle.setObjectName("yenizimmetle")
        self.gridLayout.addWidget(self.yenizimmetle, 5, 1, 1, 1)
        self.stickerid_combobox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stickerid_combobox.setFont(font)
        self.stickerid_combobox.setObjectName("stickerid_combobox")
        self.gridLayout.addWidget(self.stickerid_combobox, 3, 1, 1, 1)
        self.stickerid_combobox.setMinimumHeight(40)
        self.yenizimmetle.setMinimumHeight(40)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.urunbilgilerduzenle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.urunbilgilerduzenle.setFont(font)
        self.urunbilgilerduzenle.setObjectName("urunbilgilerduzenle")
        self.gridLayout.addWidget(self.urunbilgilerduzenle, 1, 1, 2, 1)
        self.geributtonyenizimmet = QtWidgets.QCommandLinkButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/pngtree-vector-back-icon-png-image_4190818.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.geributtonyenizimmet.setIcon(icon)
        self.geributtonyenizimmet.setIconSize(QtCore.QSize(60, 60))
        self.geributtonyenizimmet.setObjectName("geributtonyenizimmet")
        self.gridLayout.addWidget(self.geributtonyenizimmet, 10, 1, 1, 1)
        self.yenileyenizimmetbutton = QtWidgets.QCommandLinkButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/png-transparent-computer-icons-refresh-computer-monochrome-arrow-icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.yenileyenizimmetbutton.setIcon(icon1)
        self.yenileyenizimmetbutton.setIconSize(QtCore.QSize(60, 60))
        self.yenileyenizimmetbutton.setObjectName("yenileyenizimmetbutton")
        self.gridLayout.addWidget(self.yenileyenizimmetbutton, 10, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Zimmetlenecek Şahıs: "))
        self.label_2.setText(_translate("MainWindow", "Sticker ID: "))
        self.yenizimmetbilgi_text.setText(_translate("MainWindow", ""))
        self.zimmetlekaydetyeni_button.setText(_translate("MainWindow", "Zimmetle"))
        self.label.setText(_translate("MainWindow", "Seçilmiş ürün: "))
        self.urunbilgilerduzenle.setText(_translate("MainWindow", ""))
        self.geributtonyenizimmet.setText(_translate("MainWindow", "GERİ"))
        self.yenileyenizimmetbutton.setText(_translate("MainWindow", "YENİLE"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    screen = app.primaryScreen()
    if screen is not None:
        screen_geometry = screen.geometry()
        x = (screen_geometry.width() - MainWindow.width()) // 2
        y = (screen_geometry.height() - MainWindow.height()) // 2
        MainWindow.move(x, y)

    MainWindow.show()
    sys.exit(app.exec_())